name: tic_tact_oe
description: "A sleek, modern Tic Tac Toe app in Flutter."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  avatar_glow: ^2.0.2
  google_fonts: ^6.2.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.4

flutter:

  uses-material-design: true

  assets:
    - lib/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/images/icon.png" # Use your custom icon here

flutter_native_splash:
  color: "#121212" # Matches your dark background
  image: lib/images/icon.png # Your splash logo
  android: true
  ios: true
  web: false
